-- Reverse of the timestamptz migration run at 2026-08-12T07:42:43.576Z
-- Restores every column below to `timestamp` (without time zone),
-- reinterpreting the stored instant back into America/Los_Angeles wall-clock text.
-- Apply with:  psql "$DATABASE_URL" -f rollback-timestamptz-2026-08-12T07-42-43-576Z.sql

ALTER TABLE "announcements" ALTER COLUMN "timestamp" TYPE timestamp USING "timestamp" AT TIME ZONE 'America/Los_Angeles';
ALTER TABLE "announcements" ALTER COLUMN "timestamp" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "calendar_events" ALTER COLUMN "created_at" TYPE timestamp USING "created_at" AT TIME ZONE 'America/Los_Angeles';
ALTER TABLE "calendar_events" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "calendar_feed_tokens" ALTER COLUMN "created_at" TYPE timestamp USING "created_at" AT TIME ZONE 'America/Los_Angeles';
ALTER TABLE "calendar_feed_tokens" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "certification_requests" ALTER COLUMN "requested_at" TYPE timestamp USING "requested_at" AT TIME ZONE 'America/Los_Angeles';
ALTER TABLE "certification_requests" ALTER COLUMN "requested_at" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "certification_requests" ALTER COLUMN "updated_at" TYPE timestamp USING "updated_at" AT TIME ZONE 'America/Los_Angeles';
ALTER TABLE "certification_requests" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "competition_assignments" ALTER COLUMN "created_at" TYPE timestamp USING "created_at" AT TIME ZONE 'America/Los_Angeles';
ALTER TABLE "competition_assignments" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "competition_assignments" ALTER COLUMN "updated_at" TYPE timestamp USING "updated_at" AT TIME ZONE 'America/Los_Angeles';
ALTER TABLE "competition_assignments" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "competition_checkin_audit" ALTER COLUMN "created_at" TYPE timestamp USING "created_at" AT TIME ZONE 'America/Los_Angeles';
ALTER TABLE "competition_checkin_audit" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "competition_checkins" ALTER COLUMN "approved_at" TYPE timestamp USING "approved_at" AT TIME ZONE 'America/Los_Angeles';
ALTER TABLE "competition_checkins" ALTER COLUMN "check_in_at" TYPE timestamp USING "check_in_at" AT TIME ZONE 'America/Los_Angeles';
ALTER TABLE "competition_checkins" ALTER COLUMN "check_out_at" TYPE timestamp USING "check_out_at" AT TIME ZONE 'America/Los_Angeles';
ALTER TABLE "competition_checkins" ALTER COLUMN "created_at" TYPE timestamp USING "created_at" AT TIME ZONE 'America/Los_Angeles';
ALTER TABLE "competition_checkins" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "event_info" ALTER COLUMN "updated_at" TYPE timestamp USING "updated_at" AT TIME ZONE 'America/Los_Angeles';
ALTER TABLE "event_info" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "event_signups" ALTER COLUMN "approved_at" TYPE timestamp USING "approved_at" AT TIME ZONE 'America/Los_Angeles';
ALTER TABLE "event_signups" ALTER COLUMN "checked_in_at" TYPE timestamp USING "checked_in_at" AT TIME ZONE 'America/Los_Angeles';
ALTER TABLE "event_signups" ALTER COLUMN "checked_out_at" TYPE timestamp USING "checked_out_at" AT TIME ZONE 'America/Los_Angeles';
ALTER TABLE "event_signups" ALTER COLUMN "created_at" TYPE timestamp USING "created_at" AT TIME ZONE 'America/Los_Angeles';
ALTER TABLE "event_signups" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "event_signups" ALTER COLUMN "invited_at" TYPE timestamp USING "invited_at" AT TIME ZONE 'America/Los_Angeles';
ALTER TABLE "fullscreen_alerts" ALTER COLUMN "created_at" TYPE timestamp USING "created_at" AT TIME ZONE 'America/Los_Angeles';
ALTER TABLE "fullscreen_alerts" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "fullscreen_alerts" ALTER COLUMN "expires_at" TYPE timestamp USING "expires_at" AT TIME ZONE 'America/Los_Angeles';
ALTER TABLE "fundraising_entries" ALTER COLUMN "created_at" TYPE timestamp USING "created_at" AT TIME ZONE 'America/Los_Angeles';
ALTER TABLE "fundraising_entries" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "fundraising_entries" ALTER COLUMN "verified_at" TYPE timestamp USING "verified_at" AT TIME ZONE 'America/Los_Angeles';
ALTER TABLE "general_tasks" ALTER COLUMN "created_at" TYPE timestamp USING "created_at" AT TIME ZONE 'America/Los_Angeles';
ALTER TABLE "general_tasks" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "guest_tokens" ALTER COLUMN "created_at" TYPE timestamp USING "created_at" AT TIME ZONE 'America/Los_Angeles';
ALTER TABLE "guest_tokens" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "match_exceptions" ALTER COLUMN "created_at" TYPE timestamp USING "created_at" AT TIME ZONE 'America/Los_Angeles';
ALTER TABLE "match_exceptions" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "match_scouts" ALTER COLUMN "created_at" TYPE timestamp USING "created_at" AT TIME ZONE 'America/Los_Angeles';
ALTER TABLE "match_scouts" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "notifications" ALTER COLUMN "timestamp" TYPE timestamp USING "timestamp" AT TIME ZONE 'America/Los_Angeles';
ALTER TABLE "notifications" ALTER COLUMN "timestamp" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "pit_scouts" ALTER COLUMN "created_at" TYPE timestamp USING "created_at" AT TIME ZONE 'America/Los_Angeles';
ALTER TABLE "pit_scouts" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "pit_scouts" ALTER COLUMN "updated_at" TYPE timestamp USING "updated_at" AT TIME ZONE 'America/Los_Angeles';
ALTER TABLE "pit_scouts" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "projects" ALTER COLUMN "created_at" TYPE timestamp USING "created_at" AT TIME ZONE 'America/Los_Angeles';
ALTER TABLE "projects" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "push_subscriptions" ALTER COLUMN "created_at" TYPE timestamp USING "created_at" AT TIME ZONE 'America/Los_Angeles';
ALTER TABLE "push_subscriptions" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "recurring_task_templates" ALTER COLUMN "created_at" TYPE timestamp USING "created_at" AT TIME ZONE 'America/Los_Angeles';
ALTER TABLE "recurring_task_templates" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "resources" ALTER COLUMN "created_at" TYPE timestamp USING "created_at" AT TIME ZONE 'America/Los_Angeles';
ALTER TABLE "resources" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "safety_certifications" ALTER COLUMN "created_at" TYPE timestamp USING "created_at" AT TIME ZONE 'America/Los_Angeles';
ALTER TABLE "safety_certifications" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "scout_events" ALTER COLUMN "created_at" TYPE timestamp USING "created_at" AT TIME ZONE 'America/Los_Angeles';
ALTER TABLE "scout_events" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "scouting_templates" ALTER COLUMN "created_at" TYPE timestamp USING "created_at" AT TIME ZONE 'America/Los_Angeles';
ALTER TABLE "scouting_templates" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "seasons" ALTER COLUMN "created_at" TYPE timestamp USING "created_at" AT TIME ZONE 'America/Los_Angeles';
ALTER TABLE "seasons" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "tasks" ALTER COLUMN "completed_at" TYPE timestamp USING "completed_at" AT TIME ZONE 'America/Los_Angeles';
ALTER TABLE "tasks" ALTER COLUMN "created_at" TYPE timestamp USING "created_at" AT TIME ZONE 'America/Los_Angeles';
ALTER TABLE "tasks" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "team_claims" ALTER COLUMN "claimed_at" TYPE timestamp USING "claimed_at" AT TIME ZONE 'America/Los_Angeles';
ALTER TABLE "team_claims" ALTER COLUMN "claimed_at" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "team_settings" ALTER COLUMN "updated_at" TYPE timestamp USING "updated_at" AT TIME ZONE 'America/Los_Angeles';
ALTER TABLE "team_settings" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "time_entries" ALTER COLUMN "check_in_at" TYPE timestamp USING "check_in_at" AT TIME ZONE 'America/Los_Angeles';
ALTER TABLE "time_entries" ALTER COLUMN "check_in_confirmed_at" TYPE timestamp USING "check_in_confirmed_at" AT TIME ZONE 'America/Los_Angeles';
ALTER TABLE "time_entries" ALTER COLUMN "check_out_at" TYPE timestamp USING "check_out_at" AT TIME ZONE 'America/Los_Angeles';
ALTER TABLE "time_entries" ALTER COLUMN "check_out_confirmed_at" TYPE timestamp USING "check_out_confirmed_at" AT TIME ZONE 'America/Los_Angeles';
ALTER TABLE "time_entries" ALTER COLUMN "created_at" TYPE timestamp USING "created_at" AT TIME ZONE 'America/Los_Angeles';
ALTER TABLE "time_entries" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "time_entry_audit" ALTER COLUMN "created_at" TYPE timestamp USING "created_at" AT TIME ZONE 'America/Los_Angeles';
ALTER TABLE "time_entry_audit" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "user_certifications" ALTER COLUMN "granted_at" TYPE timestamp USING "granted_at" AT TIME ZONE 'America/Los_Angeles';
ALTER TABLE "user_certifications" ALTER COLUMN "granted_at" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "users" ALTER COLUMN "created_at" TYPE timestamp USING "created_at" AT TIME ZONE 'America/Los_Angeles';
ALTER TABLE "users" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP;
