/**
 * Connecting the team's Facebook Page + linked Instagram account (Coach only).
 *
 *   Facebook Login → short-lived user token → long-lived user token →
 *   Page access token (does not expire when derived from a long-lived user
 *   token) → the Page's linked Instagram professional account.
 *
 * Instagram publishing uses the Page token of the Page it's linked to.
 */
import { GraphError, graphGet, GRAPH_VERSION } from "./graph";
import { appBaseUrl } from "./signing";
import { upsertAccount } from "./store";
import { SocialError } from "./service";

export const SCOPES = [
  "pages_show_list",
  "pages_manage_posts",
  "pages_read_engagement",
  "instagram_basic",
  "instagram_content_publish",
  // Lets a future "remove from Instagram" action DELETE published media.
  "instagram_manage_contents",
  "business_management",
];

export function metaConfigured(): boolean {
  return Boolean(process.env.META_APP_ID && process.env.META_APP_SECRET);
}

export function redirectUri(): string {
  return `${appBaseUrl()}/api/social/meta/callback`;
}

/**
 * Facebook Login for Business apps log in against a saved *configuration*
 * (META_LOGIN_CONFIG_ID) that fixes the token type, assets and permissions —
 * the team uses a never-expiring System User token, so publishing survives a
 * coach leaving or changing their Facebook password. Without a configuration
 * we fall back to asking for SCOPES directly (classic Facebook Login).
 */
export function buildLoginUrl(state: string): string {
  const url = new URL(`https://www.facebook.com/${GRAPH_VERSION}/dialog/oauth`);
  url.searchParams.set("client_id", process.env.META_APP_ID || "");
  url.searchParams.set("redirect_uri", redirectUri());
  url.searchParams.set("state", state);
  url.searchParams.set("response_type", "code");
  const configId = process.env.META_LOGIN_CONFIG_ID;
  if (configId) {
    url.searchParams.set("config_id", configId);
    url.searchParams.set("override_default_response_type", "true");
  } else {
    url.searchParams.set("scope", SCOPES.join(","));
  }
  return url.toString();
}

interface PageInfo {
  id: string;
  name: string;
  access_token: string;
  instagram_business_account?: { id: string; username?: string };
}

/** Exchange the OAuth code and store every Page (and linked IG account) the
 *  coach granted. Returns what was connected. */
export async function completeConnection(code: string, connectedBy: number): Promise<{ pages: number; instagram: number }> {
  const appParams = { client_id: process.env.META_APP_ID || "", client_secret: process.env.META_APP_SECRET || "" };
  const first = await graphGet("oauth/access_token", { ...appParams, redirect_uri: redirectUri(), code });
  let token = String(first.access_token);
  // A user token from the code is short-lived (~1h), and Page tokens derived
  // from it would expire with it — swap it for a long-lived one. A System User
  // token from a "never expires" configuration is already permanent and Meta
  // may refuse the swap, so keep the original rather than failing the connect.
  try {
    const long = await graphGet("oauth/access_token", {
      ...appParams,
      grant_type: "fb_exchange_token",
      fb_exchange_token: token,
    });
    if (long?.access_token) token = String(long.access_token);
  } catch (e) {
    if (e instanceof GraphError && e.isAuthError) throw e;
    console.warn("Long-lived token exchange skipped:", (e as Error)?.message);
  }
  return storePagesForToken(token, connectedBy);
}

/**
 * Connect with a System User token generated by hand in Meta Business
 * Settings (Users → System users → Generate token). This is Meta's standard
 * route for a business connecting its OWN Page: no login dialog, and the
 * token never expires. (The Login-for-Business dialog can also mint system
 * user tokens, but Meta aims that at Tech Provider apps and it fails with a
 * generic error for ours.)
 */
export async function connectWithSystemUserToken(token: string, connectedBy: number) {
  const t = token.trim();
  if (!/^[A-Za-z0-9]{40,}$/.test(t)) {
    throw new SocialError(400, "That doesn't look like a Meta access token. Copy the whole token from Business Settings.");
  }
  // Fails fast with a clear GraphError if the token is invalid or expired.
  await graphGet("me", { fields: "id,name" }, t);
  const result = await storePagesForToken(t, connectedBy);
  if (result.pages === 0) {
    throw new SocialError(400, "The token works, but it can't see any Facebook Pages. In Business Settings → System users, assign the team Page (Full control) and the Instagram account to this system user, then generate a new token.");
  }
  return result;
}

/** List the Pages a token can manage and store each Page plus its linked
 *  Instagram account. Page tokens derived from a long-lived user token or a
 *  system user token don't expire. */
async function storePagesForToken(token: string, connectedBy: number): Promise<{ pages: number; instagram: number }> {
  const pagesRes = await graphGet(
    "me/accounts",
    { fields: "id,name,access_token,instagram_business_account{id,username}" },
    token,
  );
  const pages = (pagesRes.data || []) as PageInfo[];

  let instagram = 0;
  for (const page of pages) {
    await upsertAccount({ platform: "facebook", externalId: page.id, name: page.name, token: page.access_token, connectedBy });
    const ig = page.instagram_business_account;
    if (ig?.id) {
      await upsertAccount({
        platform: "instagram",
        externalId: ig.id,
        name: ig.username ? `@${ig.username}` : `${page.name} (Instagram)`,
        token: page.access_token,
        connectedBy,
      });
      instagram++;
    }
  }
  return { pages: pages.length, instagram };
}
